# Generated by Django 2.2.10 on 2020-04-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='id',
        ),
        migrations.AddField(
            model_name='recurso',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_creacion',
            field=models.ManyToManyField(related_name='creacion_proyecto', to='gestion.Recurso'),
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario_creacion',
            field=models.ManyToManyField(related_name='creacion_tarea', to='gestion.Recurso'),
        ),
    ]
